name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create archive
        shell: powershell
        run: |
          # Define the files/folders to include
          $items = @("fxmanifest.lua", "client/", "server/", "config/", "shared/", "README.md")
          # Create the zip file
          Compress-Archive -Path $items -DestinationPath filo_muffler.zip


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            filo_muffler.zip
          generate_release_notes: true
